settings:
  legacy:
    force: false
    interval: 0s
server:
    status: true               // server status
    open: true                 // open browser at start
    host: localhost             // server host
    port: 8080  
schema:
- name: backend
  path: .
  commands: 
     run:
        status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
  
